# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import mdstream_pb2 as mdstream__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mdstream_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MDStreamStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamResults = channel.unary_stream(
                '/mdstream.MDStream/StreamResults',
                request_serializer=mdstream__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=mdstream__pb2.Result.FromString,
                _registered_method=True)


class MDStreamServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamResults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MDStreamServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamResults': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamResults,
                    request_deserializer=mdstream__pb2.SubscribeRequest.FromString,
                    response_serializer=mdstream__pb2.Result.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mdstream.MDStream', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mdstream.MDStream', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MDStream(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/mdstream.MDStream/StreamResults',
            mdstream__pb2.SubscribeRequest.SerializeToString,
            mdstream__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
