# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mdstream.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'mdstream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emdstream.proto\x12\x08mdstream\"A\n\x04Tick\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x01\x12\x0e\n\x06volume\x18\x03 \x01(\x03\x12\n\n\x02ts\x18\x04 \x01(\x03\"\'\n\x06Result\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\"\x12\n\x10SubscribeRequest2K\n\x08MDStream\x12?\n\rStreamResults\x12\x1a.mdstream.SubscribeRequest\x1a\x10.mdstream.Result0\x01\x42\x1eZ\x1cmd_stream_engine/proto;protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mdstream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\034md_stream_engine/proto;proto'
  _globals['_TICK']._serialized_start=28
  _globals['_TICK']._serialized_end=93
  _globals['_RESULT']._serialized_start=95
  _globals['_RESULT']._serialized_end=134
  _globals['_SUBSCRIBEREQUEST']._serialized_start=136
  _globals['_SUBSCRIBEREQUEST']._serialized_end=154
  _globals['_MDSTREAM']._serialized_start=156
  _globals['_MDSTREAM']._serialized_end=231
# @@protoc_insertion_point(module_scope)
