// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: proto/mdstream.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MDStream_StreamResults_FullMethodName = "/mdstream.MDStream/StreamResults"
)

// MDStreamClient is the client API for MDStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MDStreamClient interface {
	StreamResults(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Result], error)
}

type mDStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewMDStreamClient(cc grpc.ClientConnInterface) MDStreamClient {
	return &mDStreamClient{cc}
}

func (c *mDStreamClient) StreamResults(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Result], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MDStream_ServiceDesc.Streams[0], MDStream_StreamResults_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, Result]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MDStream_StreamResultsClient = grpc.ServerStreamingClient[Result]

// MDStreamServer is the server API for MDStream service.
// All implementations must embed UnimplementedMDStreamServer
// for forward compatibility.
type MDStreamServer interface {
	StreamResults(*SubscribeRequest, grpc.ServerStreamingServer[Result]) error
	mustEmbedUnimplementedMDStreamServer()
}

// UnimplementedMDStreamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMDStreamServer struct{}

func (UnimplementedMDStreamServer) StreamResults(*SubscribeRequest, grpc.ServerStreamingServer[Result]) error {
	return status.Error(codes.Unimplemented, "method StreamResults not implemented")
}
func (UnimplementedMDStreamServer) mustEmbedUnimplementedMDStreamServer() {}
func (UnimplementedMDStreamServer) testEmbeddedByValue()                  {}

// UnsafeMDStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MDStreamServer will
// result in compilation errors.
type UnsafeMDStreamServer interface {
	mustEmbedUnimplementedMDStreamServer()
}

func RegisterMDStreamServer(s grpc.ServiceRegistrar, srv MDStreamServer) {
	// If the following call panics, it indicates UnimplementedMDStreamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MDStream_ServiceDesc, srv)
}

func _MDStream_StreamResults_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MDStreamServer).StreamResults(m, &grpc.GenericServerStream[SubscribeRequest, Result]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MDStream_StreamResultsServer = grpc.ServerStreamingServer[Result]

// MDStream_ServiceDesc is the grpc.ServiceDesc for MDStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MDStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mdstream.MDStream",
	HandlerType: (*MDStreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamResults",
			Handler:       _MDStream_StreamResults_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/mdstream.proto",
}
