// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/mdstream.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tick struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Volume        int64                  `protobuf:"varint,3,opt,name=volume,proto3" json:"volume,omitempty"`
	Ts            int64                  `protobuf:"varint,4,opt,name=ts,proto3" json:"ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tick) Reset() {
	*x = Tick{}
	mi := &file_proto_mdstream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tick) ProtoMessage() {}

func (x *Tick) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mdstream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tick.ProtoReflect.Descriptor instead.
func (*Tick) Descriptor() ([]byte, []int) {
	return file_proto_mdstream_proto_rawDescGZIP(), []int{0}
}

func (x *Tick) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Tick) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Tick) GetVolume() int64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *Tick) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_proto_mdstream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mdstream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_proto_mdstream_proto_rawDescGZIP(), []int{1}
}

func (x *Result) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Result) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_proto_mdstream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mdstream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_mdstream_proto_rawDescGZIP(), []int{2}
}

var File_proto_mdstream_proto protoreflect.FileDescriptor

const file_proto_mdstream_proto_rawDesc = "" +
	"\n" +
	"\x14proto/mdstream.proto\x12\bmdstream\"\\\n" +
	"\x04Tick\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12\x16\n" +
	"\x06volume\x18\x03 \x01(\x03R\x06volume\x12\x0e\n" +
	"\x02ts\x18\x04 \x01(\x03R\x02ts\"6\n" +
	"\x06Result\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\"\x12\n" +
	"\x10SubscribeRequest2K\n" +
	"\bMDStream\x12?\n" +
	"\rStreamResults\x12\x1a.mdstream.SubscribeRequest\x1a\x10.mdstream.Result0\x01B\x1eZ\x1cmd_stream_engine/proto;protob\x06proto3"

var (
	file_proto_mdstream_proto_rawDescOnce sync.Once
	file_proto_mdstream_proto_rawDescData []byte
)

func file_proto_mdstream_proto_rawDescGZIP() []byte {
	file_proto_mdstream_proto_rawDescOnce.Do(func() {
		file_proto_mdstream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mdstream_proto_rawDesc), len(file_proto_mdstream_proto_rawDesc)))
	})
	return file_proto_mdstream_proto_rawDescData
}

var file_proto_mdstream_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_mdstream_proto_goTypes = []any{
	(*Tick)(nil),             // 0: mdstream.Tick
	(*Result)(nil),           // 1: mdstream.Result
	(*SubscribeRequest)(nil), // 2: mdstream.SubscribeRequest
}
var file_proto_mdstream_proto_depIdxs = []int32{
	2, // 0: mdstream.MDStream.StreamResults:input_type -> mdstream.SubscribeRequest
	1, // 1: mdstream.MDStream.StreamResults:output_type -> mdstream.Result
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_mdstream_proto_init() }
func file_proto_mdstream_proto_init() {
	if File_proto_mdstream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mdstream_proto_rawDesc), len(file_proto_mdstream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mdstream_proto_goTypes,
		DependencyIndexes: file_proto_mdstream_proto_depIdxs,
		MessageInfos:      file_proto_mdstream_proto_msgTypes,
	}.Build()
	File_proto_mdstream_proto = out.File
	file_proto_mdstream_proto_goTypes = nil
	file_proto_mdstream_proto_depIdxs = nil
}
